### ISSUE TITLE
Can you provide another link for the JCU fish dataset?

### ISSUE THREAD

**Issue by BJTUJia** [IssamLaradji/affinity_lcfcn#1]
Hi there, thanks for this interesting work. However, the fish dataset link can't be accessed here in China. Is it the same as https://cloudstor.aarnet.edu.au/plus/s/NfjObIhtUYO6332 ? I suppose not,  since you use different annotations. Can you provide another link that can be easily accessed? Thanks a lot!

**Comment by IssamLaradji** [comment]
Sorry I just saw this `issue`, were you able to download the dataset?
